server:
  privateFiles: /nfs/farm/groups/iota/development
  errors:
    display: true
    severity: warning
    displayApiErrors: false
  saveSession: true

client:
  baseUrl: http://groups.engr.oregonstate.edu/iota-dev/

logger:
  level: trace

database:
  configFile: /nfs/farm/groups/iota/development/database.yaml