server:
  privateFiles: /nfs/farm/groups/iota/production
  errors:
    display: false
    displayApiErrors: false
  saveSession: true

client:
  baseUrl: http://groups.engr.oregonstate.edu/iota/

logger:
  level: info

database:
  configFile: /nfs/farm/groups/iota/production/database.yaml