server:
  privateFiles: /nfs/farm/groups/iota
  errors:
    display: false
    displayApiErrors: false
  saveSession: true

client:
  baseUrl: http://groups.engr.oregonstate.edu/IOTA/

logger:
  level: info

database:
  configFile: /nfs/farm/groups/iota/database.yaml